name: checking out repo using github actions #name of workflow
on: [push] # when workflow should run
jobs: 
    checkout-repo: #job name
        runs-on: ubuntu-latest #docker image on which job will run
        steps:
            - users: actions/checkout@v2
            - run: tree